#port
server:
  port: 8082
#eureka config
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8087/eureka/
spring:
  application:
    name: order-provider
