#Server port
server:
  port: 8081

#eureka-server 注册名
spring:
  application:
    name: gateway
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8087/eureka/
feign:
  client:
    config:
      default:
        connectionTimeout: 5000  #连接超时时间
        readTimeout: 5000 #读超时时间
        loggerLevel:  full #日志级别
