#Server port
server:
  port: 8081

#eureka-server 注册名
spring:
  application:
    name: gateway
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8087/eureka/

